baseurl: /learning-nix
permalink: /:year-:title
show_downloads: false # variable for 'cayman' theme
title: My experience learning nix
theme: jekyll-theme-cayman
timezone: Europe/London
#github:
#  is_project_page: false
